// 1년치 블로그 주제 (365개) — 7개 카테고리 × 52주 + 1
// 카테고리: guide(월), cosmetics(화), faq(수), event(목), compare(금), ingredient(토), tips(일)

export const TOPICS = [
  // ═══════════════════════════════════════════════════════════════
  // GUIDE — 시술 가이드 (52개)
  // ═══════════════════════════════════════════════════════════════
  { category: "guide", keyword: "rhinoplasty in Korea complete guide" },
  { category: "guide", keyword: "double eyelid surgery Korea guide" },
  { category: "guide", keyword: "facial contouring V-line surgery Korea" },
  { category: "guide", keyword: "liposuction in Korea what to expect" },
  { category: "guide", keyword: "breast augmentation Korea guide" },
  { category: "guide", keyword: "botox injections Korea guide" },
  { category: "guide", keyword: "dermal filler Korea complete guide" },
  { category: "guide", keyword: "laser toning Korea skin treatment" },
  { category: "guide", keyword: "ultherapy HIFU Korea guide" },
  { category: "guide", keyword: "skin lifting thread lift Korea" },
  { category: "guide", keyword: "acne treatment Korea dermatology" },
  { category: "guide", keyword: "teeth whitening Korea dental guide" },
  { category: "guide", keyword: "dental braces orthodontics Korea" },
  { category: "guide", keyword: "dental implant Korea complete guide" },
  { category: "guide", keyword: "dental veneer Korea guide" },
  { category: "guide", keyword: "LASIK surgery Korea vision correction" },
  { category: "guide", keyword: "LASEK surgery Korea eye treatment" },
  { category: "guide", keyword: "hair transplant Korea FUE guide" },
  { category: "guide", keyword: "fat grafting Korea facial rejuvenation" },
  { category: "guide", keyword: "jaw reduction surgery Korea" },
  { category: "guide", keyword: "cheekbone reduction Korea guide" },
  { category: "guide", keyword: "chin augmentation Korea genioplasty" },
  { category: "guide", keyword: "eye bag removal Korea blepharoplasty" },
  { category: "guide", keyword: "forehead lift Korea endoscopic" },
  { category: "guide", keyword: "lip filler Korea natural results" },
  { category: "guide", keyword: "scar treatment Korea laser options" },
  { category: "guide", keyword: "tattoo removal Korea laser guide" },
  { category: "guide", keyword: "mole removal Korea dermatology" },
  { category: "guide", keyword: "wrinkle treatment Korea anti-aging" },
  { category: "guide", keyword: "skin booster injection Korea guide" },
  { category: "guide", keyword: "PDO thread lift Korea guide" },
  { category: "guide", keyword: "fraxel laser Korea skin resurfacing" },
  { category: "guide", keyword: "PRP treatment Korea platelet therapy" },
  { category: "guide", keyword: "Invisalign clear aligners Korea" },
  { category: "guide", keyword: "ICL implantable lens Korea guide" },
  { category: "guide", keyword: "SMILE laser eye surgery Korea" },
  { category: "guide", keyword: "calf reduction Korea botox surgery" },
  { category: "guide", keyword: "arm liposuction Korea guide" },
  { category: "guide", keyword: "tummy tuck abdominoplasty Korea" },
  { category: "guide", keyword: "male plastic surgery Korea guide" },
  { category: "guide", keyword: "revision rhinoplasty Korea specialist" },
  { category: "guide", keyword: "under eye fat repositioning Korea" },
  { category: "guide", keyword: "neck lift Korea rejuvenation" },
  { category: "guide", keyword: "ear surgery otoplasty Korea" },
  { category: "guide", keyword: "dimple creation surgery Korea" },
  { category: "guide", keyword: "hairline correction Korea transplant" },
  { category: "guide", keyword: "scalp micropigmentation Korea SMP" },
  { category: "guide", keyword: "body contouring Korea non-surgical" },
  { category: "guide", keyword: "Korean health checkup comprehensive" },
  { category: "guide", keyword: "endoscopy colonoscopy Korea guide" },
  { category: "guide", keyword: "IVF fertility treatment Korea" },
  { category: "guide", keyword: "spine treatment Korea orthopedic" },

  // ═══════════════════════════════════════════════════════════════
  // COSMETICS — 화장품 순위 (52개)
  // ═══════════════════════════════════════════════════════════════
  { category: "cosmetics", keyword: "best Korean sunscreen 2026 ranking" },
  { category: "cosmetics", keyword: "best Korean moisturizer all skin types" },
  { category: "cosmetics", keyword: "best Korean serum for glowing skin" },
  { category: "cosmetics", keyword: "best Korean cleanser gentle foam" },
  { category: "cosmetics", keyword: "best Korean toner hydrating ranking" },
  { category: "cosmetics", keyword: "best Korean eye cream anti-aging" },
  { category: "cosmetics", keyword: "best Korean sheet mask top 10" },
  { category: "cosmetics", keyword: "best Korean lip tint popular colors" },
  { category: "cosmetics", keyword: "best Korean retinol product ranking" },
  { category: "cosmetics", keyword: "Korean skincare for oily skin best" },
  { category: "cosmetics", keyword: "Korean skincare for dry skin winter" },
  { category: "cosmetics", keyword: "Korean anti-aging skincare over 30" },
  { category: "cosmetics", keyword: "Korean skincare for sensitive skin" },
  { category: "cosmetics", keyword: "Korean skincare for acne prone skin" },
  { category: "cosmetics", keyword: "best Korean BB cream CC cream" },
  { category: "cosmetics", keyword: "best Korean cushion foundation ranking" },
  { category: "cosmetics", keyword: "best Korean exfoliator AHA BHA" },
  { category: "cosmetics", keyword: "best Korean sleeping mask overnight" },
  { category: "cosmetics", keyword: "best Korean essence vs serum guide" },
  { category: "cosmetics", keyword: "best Korean vitamin C serum brightening" },
  { category: "cosmetics", keyword: "best Korean niacinamide products" },
  { category: "cosmetics", keyword: "best Korean snail mucin products" },
  { category: "cosmetics", keyword: "best Korean centella products ranking" },
  { category: "cosmetics", keyword: "best Korean hyaluronic acid products" },
  { category: "cosmetics", keyword: "best Korean propolis skincare" },
  { category: "cosmetics", keyword: "best Korean mugwort skincare trending" },
  { category: "cosmetics", keyword: "best Korean rice skincare products" },
  { category: "cosmetics", keyword: "best Korean green tea skincare" },
  { category: "cosmetics", keyword: "best Korean skincare sets for beginners" },
  { category: "cosmetics", keyword: "best Korean mens skincare products" },
  { category: "cosmetics", keyword: "best Korean skincare under $20 budget" },
  { category: "cosmetics", keyword: "best Korean makeup primer base" },
  { category: "cosmetics", keyword: "best Korean mascara waterproof" },
  { category: "cosmetics", keyword: "best Korean blush trending colors" },
  { category: "cosmetics", keyword: "best Korean setting powder spray" },
  { category: "cosmetics", keyword: "best Korean hair care shampoo" },
  { category: "cosmetics", keyword: "best Korean body lotion cream" },
  { category: "cosmetics", keyword: "best Korean hand cream gift set" },
  { category: "cosmetics", keyword: "Korean skincare routine 10 step guide" },
  { category: "cosmetics", keyword: "Korean glass skin routine products" },
  { category: "cosmetics", keyword: "Korean skincare for teens beginners" },
  { category: "cosmetics", keyword: "Korean skincare for 40s mature skin" },
  { category: "cosmetics", keyword: "Korean organic natural skincare brands" },
  { category: "cosmetics", keyword: "Korean vegan cruelty-free skincare" },
  { category: "cosmetics", keyword: "Korean skincare for hyperpigmentation" },
  { category: "cosmetics", keyword: "Korean skincare for dark circles" },
  { category: "cosmetics", keyword: "Korean skincare for large pores" },
  { category: "cosmetics", keyword: "best Korean sunscreen for dark skin" },
  { category: "cosmetics", keyword: "Korean skincare routine for rosacea" },
  { category: "cosmetics", keyword: "best Korean dermocosmetics cica" },
  { category: "cosmetics", keyword: "Korean beauty advent calendar 2026" },
  { category: "cosmetics", keyword: "Korean skincare trends 2026 forecast" },

  // ═══════════════════════════════════════════════════════════════
  // FAQ — 자주 묻는 질문 (52개)
  // ═══════════════════════════════════════════════════════════════
  { category: "faq", keyword: "is plastic surgery safe in Korea for foreigners" },
  { category: "faq", keyword: "how to choose best clinic Korea" },
  { category: "faq", keyword: "Korean dermatology vs Western difference" },
  { category: "faq", keyword: "recovery time Korean plastic surgery" },
  { category: "faq", keyword: "do Korean clinics speak English" },
  { category: "faq", keyword: "Korean clinic consultation process explained" },
  { category: "faq", keyword: "how old do you need plastic surgery Korea" },
  { category: "faq", keyword: "can I get refund plastic surgery Korea" },
  { category: "faq", keyword: "what if something goes wrong surgery Korea" },
  { category: "faq", keyword: "how to verify Korean surgeon qualifications" },
  { category: "faq", keyword: "Korean plastic surgery before and after realistic" },
  { category: "faq", keyword: "how many follow up visits after surgery Korea" },
  { category: "faq", keyword: "can I fly after plastic surgery Korea" },
  { category: "faq", keyword: "best season visit Korea plastic surgery" },
  { category: "faq", keyword: "do Korean clinics accept international insurance" },
  { category: "faq", keyword: "how to communicate with Korean doctors" },
  { category: "faq", keyword: "what to bring first clinic visit Korea" },
  { category: "faq", keyword: "difference between hospital and clinic Korea" },
  { category: "faq", keyword: "how long should I stay Korea after surgery" },
  { category: "faq", keyword: "can I combine multiple procedures Korea" },
  { category: "faq", keyword: "is Korean dermatology better than Western" },
  { category: "faq", keyword: "how to avoid plastic surgery scams Korea" },
  { category: "faq", keyword: "what is ghost surgery Korea explained" },
  { category: "faq", keyword: "Korean clinic payment methods foreigners" },
  { category: "faq", keyword: "do I need translator Korean clinic" },
  { category: "faq", keyword: "Korean medical tourism visa requirements" },
  { category: "faq", keyword: "can men get plastic surgery Korea" },
  { category: "faq", keyword: "underage plastic surgery rules Korea" },
  { category: "faq", keyword: "Korean skincare consultation dermatologist" },
  { category: "faq", keyword: "how Korean clinics handle complications" },
  { category: "faq", keyword: "what is HIRA Korea hospital verification" },
  { category: "faq", keyword: "can I see real patient photos Korean clinic" },
  { category: "faq", keyword: "how to get medical records from Korea" },
  { category: "faq", keyword: "Korean clinic aftercare services foreigners" },
  { category: "faq", keyword: "is dental tourism Korea worth it" },
  { category: "faq", keyword: "Korean eye surgery LASIK vs LASEK difference" },
  { category: "faq", keyword: "how to prepare for surgery in Korea" },
  { category: "faq", keyword: "Korean hospital food and accommodation" },
  { category: "faq", keyword: "VAT tax refund medical services Korea" },
  { category: "faq", keyword: "can I get prescription skincare Korea" },
  { category: "faq", keyword: "Korean clinic online consultation available" },
  { category: "faq", keyword: "best Korean clinic review websites trusted" },
  { category: "faq", keyword: "why Korean plastic surgery cheaper than US" },
  { category: "faq", keyword: "Korean clinic deposit cancellation policy" },
  { category: "faq", keyword: "are Korean beauty treatments FDA approved" },
  { category: "faq", keyword: "how to research Korean clinics from abroad" },
  { category: "faq", keyword: "Korean clinic staff speak Japanese Chinese" },
  { category: "faq", keyword: "what anesthesia used Korean plastic surgery" },
  { category: "faq", keyword: "Korean clinic surgery time how long" },
  { category: "faq", keyword: "can I work remotely during recovery Korea" },
  { category: "faq", keyword: "Korean medical tourism growth statistics" },
  { category: "faq", keyword: "do Korean results look natural foreigners" },

  // ═══════════════════════════════════════════════════════════════
  // COMPARE — 비용 비교 (52개)
  // ═══════════════════════════════════════════════════════════════
  { category: "compare", keyword: "Korea vs Thailand plastic surgery cost" },
  { category: "compare", keyword: "Korea vs Turkey rhinoplasty cost comparison" },
  { category: "compare", keyword: "Korea vs Japan dermatology cost comparison" },
  { category: "compare", keyword: "Korea vs USA plastic surgery cost comparison" },
  { category: "compare", keyword: "Korea vs Mexico plastic surgery comparison" },
  { category: "compare", keyword: "Korea vs Colombia plastic surgery cost" },
  { category: "compare", keyword: "Korea vs India medical tourism cost" },
  { category: "compare", keyword: "Korea vs Taiwan cosmetic surgery cost" },
  { category: "compare", keyword: "Korea vs Vietnam dental treatment cost" },
  { category: "compare", keyword: "Korea vs UK plastic surgery cost comparison" },
  { category: "compare", keyword: "Korea vs Australia cosmetic surgery cost" },
  { category: "compare", keyword: "Korea vs Singapore dermatology cost" },
  { category: "compare", keyword: "Korea vs Dubai plastic surgery comparison" },
  { category: "compare", keyword: "Korea vs Brazil plastic surgery cost" },
  { category: "compare", keyword: "Korea vs Germany medical treatment cost" },
  { category: "compare", keyword: "Korea dental implant cost vs other countries" },
  { category: "compare", keyword: "Korea LASIK cost vs USA Europe comparison" },
  { category: "compare", keyword: "Korea hair transplant cost vs Turkey" },
  { category: "compare", keyword: "Korea botox filler cost vs Western countries" },
  { category: "compare", keyword: "Korea liposuction cost global comparison" },
  { category: "compare", keyword: "Korea facelift cost vs USA comparison" },
  { category: "compare", keyword: "Korea breast surgery cost comparison global" },
  { category: "compare", keyword: "Korea rhinoplasty cost breakdown detailed" },
  { category: "compare", keyword: "Korea double eyelid surgery cost breakdown" },
  { category: "compare", keyword: "Korea facial contouring cost breakdown" },
  { category: "compare", keyword: "Korea skin treatment laser cost guide" },
  { category: "compare", keyword: "Korea teeth whitening cost vs other countries" },
  { category: "compare", keyword: "Korea orthodontics braces cost comparison" },
  { category: "compare", keyword: "Korea health checkup cost vs Japan" },
  { category: "compare", keyword: "Korea vs Thailand dental veneer cost" },
  { category: "compare", keyword: "average plastic surgery costs Seoul 2026" },
  { category: "compare", keyword: "average dermatology treatment costs Seoul" },
  { category: "compare", keyword: "Gangnam vs Sinchon clinic price difference" },
  { category: "compare", keyword: "Seoul vs Busan medical tourism cost" },
  { category: "compare", keyword: "Korea medical tourism total trip cost" },
  { category: "compare", keyword: "hidden costs Korean plastic surgery" },
  { category: "compare", keyword: "Korea all-inclusive surgery package cost" },
  { category: "compare", keyword: "Korea premium vs budget clinic comparison" },
  { category: "compare", keyword: "Korea university hospital vs private clinic cost" },
  { category: "compare", keyword: "Korea non-surgical vs surgical treatment cost" },
  { category: "compare", keyword: "Korea anti-aging treatment cost comparison" },
  { category: "compare", keyword: "Korea acne treatment cost dermatology" },
  { category: "compare", keyword: "Korea scar treatment cost laser options" },
  { category: "compare", keyword: "Korea hair loss treatment cost comparison" },
  { category: "compare", keyword: "Korea thread lift vs facelift cost" },
  { category: "compare", keyword: "Korea ultherapy vs thermage cost" },
  { category: "compare", keyword: "Korea filler vs fat grafting cost" },
  { category: "compare", keyword: "Korea implant vs bridge dental cost" },
  { category: "compare", keyword: "Korea LASIK vs LASEK vs ICL cost" },
  { category: "compare", keyword: "Korea medical tourism cost saving tips" },
  { category: "compare", keyword: "is Korea still affordable plastic surgery 2026" },
  { category: "compare", keyword: "Korea won exchange rate surgery savings" },

  // ═══════════════════════════════════════════════════════════════
  // INGREDIENT — 성분 분석 (53개)
  // ═══════════════════════════════════════════════════════════════
  { category: "ingredient", keyword: "niacinamide Korean skincare benefits science" },
  { category: "ingredient", keyword: "snail mucin scientific evidence Korean beauty" },
  { category: "ingredient", keyword: "centella asiatica Korean skincare benefits" },
  { category: "ingredient", keyword: "hyaluronic acid Korean products explained" },
  { category: "ingredient", keyword: "retinol Korean skincare usage guide" },
  { category: "ingredient", keyword: "vitamin C serum Korean skincare science" },
  { category: "ingredient", keyword: "AHA BHA PHA Korean exfoliant explained" },
  { category: "ingredient", keyword: "ceramide Korean skincare barrier repair" },
  { category: "ingredient", keyword: "peptide Korean skincare anti-aging science" },
  { category: "ingredient", keyword: "green tea extract Korean skincare benefits" },
  { category: "ingredient", keyword: "rice extract ferment Korean skincare" },
  { category: "ingredient", keyword: "propolis Korean skincare healing benefits" },
  { category: "ingredient", keyword: "mugwort artemisia Korean skincare calming" },
  { category: "ingredient", keyword: "tea tree oil Korean acne treatment" },
  { category: "ingredient", keyword: "aloe vera Korean skincare soothing" },
  { category: "ingredient", keyword: "collagen Korean skincare does it work" },
  { category: "ingredient", keyword: "squalane Korean skincare moisturizing" },
  { category: "ingredient", keyword: "tranexamic acid Korean dark spot treatment" },
  { category: "ingredient", keyword: "arbutin Korean skincare whitening brightening" },
  { category: "ingredient", keyword: "galactomyces Korean skincare fermented" },
  { category: "ingredient", keyword: "bifida ferment Korean skincare probiotic" },
  { category: "ingredient", keyword: "madecassoside Korean skincare healing" },
  { category: "ingredient", keyword: "bakuchiol Korean retinol alternative natural" },
  { category: "ingredient", keyword: "adenosine Korean anti-wrinkle ingredient" },
  { category: "ingredient", keyword: "EGF growth factor Korean skincare" },
  { category: "ingredient", keyword: "bee venom Korean skincare anti-aging" },
  { category: "ingredient", keyword: "ginseng Korean skincare traditional ingredient" },
  { category: "ingredient", keyword: "shea butter Korean skincare moisturizer" },
  { category: "ingredient", keyword: "jojoba oil Korean skincare balancing" },
  { category: "ingredient", keyword: "zinc oxide Korean sunscreen ingredient" },
  { category: "ingredient", keyword: "salicylic acid Korean acne products" },
  { category: "ingredient", keyword: "glycolic acid Korean skincare peeling" },
  { category: "ingredient", keyword: "lactic acid Korean gentle exfoliation" },
  { category: "ingredient", keyword: "azelaic acid Korean skincare rosacea" },
  { category: "ingredient", keyword: "panthenol Korean skincare healing hydrating" },
  { category: "ingredient", keyword: "allantoin Korean skincare soothing repair" },
  { category: "ingredient", keyword: "licorice root Korean brightening ingredient" },
  { category: "ingredient", keyword: "turmeric Korean skincare anti-inflammatory" },
  { category: "ingredient", keyword: "honey Korean skincare natural humectant" },
  { category: "ingredient", keyword: "charcoal Korean skincare pore cleansing" },
  { category: "ingredient", keyword: "clay Korean skincare mask detoxifying" },
  { category: "ingredient", keyword: "rosehip oil Korean skincare regeneration" },
  { category: "ingredient", keyword: "witch hazel Korean skincare toner" },
  { category: "ingredient", keyword: "fermented soybean Korean skincare benefits" },
  { category: "ingredient", keyword: "mushroom extract Korean skincare trending" },
  { category: "ingredient", keyword: "bamboo extract Korean skincare hydration" },
  { category: "ingredient", keyword: "seaweed kelp Korean skincare marine" },
  { category: "ingredient", keyword: "salmon egg DNA Korean skincare PDRN" },
  { category: "ingredient", keyword: "exosome Korean skincare newest trend" },
  { category: "ingredient", keyword: "glutathione Korean skincare brightening" },
  { category: "ingredient", keyword: "KFDA approved ingredients vs FDA difference" },
  { category: "ingredient", keyword: "Korean skincare ingredient blacklist avoid" },
  // ═══════════════════════════════════════════════════════════════
  // TIPS — 의료관광 팁 (52개)
  // ═══════════════════════════════════════════════════════════════
  { category: "tips", keyword: "Korea medical tourism visa guide 2026" },
  { category: "tips", keyword: "Gangnam clinic area guide for foreigners" },
  { category: "tips", keyword: "Seoul medical tourism budget planning" },
  { category: "tips", keyword: "Korea clinic first visit checklist" },
  { category: "tips", keyword: "Korea medical tourism insurance guide" },
  { category: "tips", keyword: "best time to visit Korea beauty treatment" },
  { category: "tips", keyword: "Incheon airport to Gangnam clinic transport" },
  { category: "tips", keyword: "Seoul hotel near clinic recovery stay" },
  { category: "tips", keyword: "what to pack Korea surgery trip" },
  { category: "tips", keyword: "Korean SIM card WiFi medical tourist" },
  { category: "tips", keyword: "Korean food diet after plastic surgery" },
  { category: "tips", keyword: "Gangnam beauty district walking tour" },
  { category: "tips", keyword: "Seoul beauty shopping Myeongdong guide" },
  { category: "tips", keyword: "Korea surgery recovery Airbnb tips" },
  { category: "tips", keyword: "solo travel Korea medical tourism female" },
  { category: "tips", keyword: "Korea medical tourism with family tips" },
  { category: "tips", keyword: "how to book Korean clinic from abroad" },
  { category: "tips", keyword: "Korean clinic email consultation template" },
  { category: "tips", keyword: "Korea medical tourism packing list winter" },
  { category: "tips", keyword: "Korea medical tourism packing list summer" },
  { category: "tips", keyword: "Seoul free activities during recovery" },
  { category: "tips", keyword: "Korean pharmacy guide for foreigners" },
  { category: "tips", keyword: "emergency contacts Korea medical tourist" },
  { category: "tips", keyword: "Korean hospital etiquette culture tips" },
  { category: "tips", keyword: "money exchange tips Korea medical tourist" },
  { category: "tips", keyword: "Korea T-money card transportation guide" },
  { category: "tips", keyword: "Seoul subway guide medical tourist" },
  { category: "tips", keyword: "Busan medical tourism alternative Seoul" },
  { category: "tips", keyword: "Jeju Island recovery vacation after surgery" },
  { category: "tips", keyword: "Korea medical tourism itinerary 7 days" },
  { category: "tips", keyword: "Korea medical tourism itinerary 14 days" },
  { category: "tips", keyword: "Korea beauty tourism spring cherry blossom" },
  { category: "tips", keyword: "Korea beauty tourism autumn foliage" },
  { category: "tips", keyword: "Korea medical tourism during winter tips" },
  { category: "tips", keyword: "Korean spa jjimjilbang after treatment" },
  { category: "tips", keyword: "duty free shopping Korea beauty products" },
  { category: "tips", keyword: "Olive Young shopping guide best products" },
  { category: "tips", keyword: "Korea beauty haul must-buy list" },
  { category: "tips", keyword: "photographing recovery Korea privacy tips" },
  { category: "tips", keyword: "Korean clinic review how to write helpful" },
  { category: "tips", keyword: "connecting with other medical tourists Korea" },
  { category: "tips", keyword: "Korea medical tourism for Chinese patients" },
  { category: "tips", keyword: "Korea medical tourism for Japanese patients" },
  { category: "tips", keyword: "Korea medical tourism for Vietnamese patients" },
  { category: "tips", keyword: "Korea medical tourism for Russian patients" },
  { category: "tips", keyword: "Korea medical tourism for Thai patients" },
  { category: "tips", keyword: "Korea medical tourism for Mongolian patients" },
  { category: "tips", keyword: "Korea medical tourism for American patients" },
  { category: "tips", keyword: "Korea medical tourism for European patients" },
  { category: "tips", keyword: "Korea medical tourism for Middle East patients" },
  { category: "tips", keyword: "Korea medical tourism for Southeast Asian" },
  { category: "tips", keyword: "returning home after Korea surgery checklist" },
  { category: "tips", keyword: "how to read Korean skincare ingredient labels" },

  // ═══════════════════════════════════════════════════════════════
  // EVENT — 병원 이벤트/트렌드 (52개)
  // ═══════════════════════════════════════════════════════════════
  { category: "event", keyword: "Korean clinic seasonal promotions guide" },
  { category: "event", keyword: "Gangnam dermatology special offers monthly" },
  { category: "event", keyword: "Korea plastic surgery new year deals" },
  { category: "event", keyword: "Korea spring beauty treatment promotions" },
  { category: "event", keyword: "Korea summer skincare clinic specials" },
  { category: "event", keyword: "Korea autumn anti-aging treatment deals" },
  { category: "event", keyword: "Korea winter surgery best timing deals" },
  { category: "event", keyword: "Korean beauty expo events calendar 2026" },
  { category: "event", keyword: "Medical Korea conference highlights" },
  { category: "event", keyword: "Korean dermatology new treatment 2026" },
  { category: "event", keyword: "Korean plastic surgery technology trends" },
  { category: "event", keyword: "new Korean skincare launch trending" },
  { category: "event", keyword: "Korean FDA new approved treatments 2026" },
  { category: "event", keyword: "Korean clinic free consultation events" },
  { category: "event", keyword: "Korea medical tourism festival events" },
  { category: "event", keyword: "Gangnam beauty week special offers" },
  { category: "event", keyword: "Korean clinic loyalty program benefits" },
  { category: "event", keyword: "Korea holiday clinic operating hours" },
  { category: "event", keyword: "Korean beauty award winning products 2026" },
  { category: "event", keyword: "Korea dermatology seminar key findings" },
  { category: "event", keyword: "trending Korean beauty treatments this month" },
  { category: "event", keyword: "Korean clinic package deals foreigners" },
  { category: "event", keyword: "Korea skin care clinic new opening" },
  { category: "event", keyword: "Korean beauty influencer recommended clinics" },
  { category: "event", keyword: "Korea medical tourism government support news" },
  { category: "event", keyword: "Korean anti-aging treatment breakthrough" },
  { category: "event", keyword: "Korean hair restoration new technique" },
  { category: "event", keyword: "Korean dental technology innovation" },
  { category: "event", keyword: "Korean eye surgery new laser technology" },
  { category: "event", keyword: "Korea wellness tourism new programs" },
  { category: "event", keyword: "Korean beauty brand collaboration clinic" },
  { category: "event", keyword: "Korea plastic surgery association updates" },
  { category: "event", keyword: "Korean dermatology research breakthroughs" },
  { category: "event", keyword: "Gangnam clinic renovation new facilities" },
  { category: "event", keyword: "Korea medical AI diagnosis new service" },
  { category: "event", keyword: "Korean telemedicine consultation service" },
  { category: "event", keyword: "Korea beauty tourism statistics monthly" },
  { category: "event", keyword: "Korean clinic certification JCI news" },
  { category: "event", keyword: "new Korean skincare ingredient discovery" },
  { category: "event", keyword: "Korean beauty trend forecast next quarter" },
  { category: "event", keyword: "Korea cosmetic surgery regulation updates" },
  { category: "event", keyword: "Korean clinic multilingual staff expansion" },
  { category: "event", keyword: "Korea medical tourism app new features" },
  { category: "event", keyword: "Korean beauty YouTube trending treatments" },
  { category: "event", keyword: "Korea derma clinic summer special programs" },
  { category: "event", keyword: "Korean clinic group discount packages" },
  { category: "event", keyword: "Korea plastic surgery recovery center new" },
  { category: "event", keyword: "Korean beauty community events meetup" },
  { category: "event", keyword: "Korea medical tourism success stories monthly" },
  { category: "event", keyword: "Korean clinic technology equipment upgrade" },
  { category: "event", keyword: "Korea beauty treatment combination trending" },
  { category: "event", keyword: "Korean wellness retreat beauty package" },
];
